### ISSUE TITLE
Crash Between GregicAdditions and... GTCE ?

### ISSUE THREAD

**Issue by LukaPix** [EmosewaPixel/GregicAdditions#39]
Sooo I really dont know what happened here

```
java.lang.ClassCastException: gregtech.api.unification.material.type.IngotMaterial cannot be cast to gregtech.api.unification.material.type.GemMaterial
	at gregicadditions.item.GAMetaTool.registerRecipes(GAMetaTool.java:53)
	at gregicadditions.item.GAMetaItems.registerRecipes(GAMetaItems.java:147)
	at gregicadditions.CommonProxy.registerRecipes(CommonProxy.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_496_CommonProxy_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at gregicadditions.item.GAMetaTool.registerRecipes(GAMetaTool.java:53)
	at gregicadditions.item.GAMetaItems.registerRecipes(GAMetaItems.java:147)
	at gregicadditions.CommonProxy.registerRecipes(CommonProxy.java:66)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_496_CommonProxy_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:623)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

```
	List of loaded APIs: 
		* actuallyadditionsapi (34) from ActuallyAdditions-1.12.2-r144.jar
		* ae2wtlib|api (1.1) from AE2WTLib-1.12.2-1.0.0.jar
		* antiqueatlasapi (5.1) from antiqueatlas-1.12.2-4.4.9.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-4.jar
		* ArtisanWorktablesAPI (5) from artisanworktables-1.12.2-1.19.5.jar
		* Baubles|API (1.4.0.2) from AE2WTLib-1.12.2-1.0.0.jar
		* betteradvancements|API (0.0.14.68) from BetterAdvancements-1.12.2-0.0.14.68.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.5-134.jar
		* BetweenlandsAPI (1.12.1) from TheBetweenlands-3.4.1-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.0.38.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|arboriculture (4.3.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|book (5.8.1) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|climate (5.0.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|core (5.7.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|farming (5.8.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|food (1.1.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|genetics (5.7.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|gui (5.8.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|lepidopterology (1.4.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|modules (5.7.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.12.2-5.8.2.374.jar
		* ForestryAPI|world (2.1.0) from forestry_1.12.2-5.8.2.374.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.12-87.jar
		* ImmersiveEngineering|ImmersiveFluxAPI (1.0) from ImmersiveEngineering-0.12-87.jar
		* industrialforegoingapi (5) from industrialforegoing-1.12.2-1.11.10-223.jar
		* jeresources|API (0.8.10.50) from JustEnoughResources-1.12.2-0.8.10.50.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.14.3.237.jar
		* MouseTweaks|API (1.0) from artisanworktables-1.12.2-1.19.5.jar
		* naturesauraapi (5) from NaturesAura-b5.jar
		* PatchouliAPI (5) from Patchouli-1.0-12.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12-2.0.35.jar
		* PsiAPI (7) from Psi-r1.1-62.jar
		* QuarkAPI (2) from Quark-r1.5-134.jar
		* reborncoreAPI (3.12.0.378) from RebornCore-1.12.2-3.12.0.378-universal.jar
		* reborncoreAPI|Power (3.12.0.378) from RebornCore-1.12.2-3.12.0.378-universal.jar
		* reborncoreAPI|Recipe (3.12.0.378) from RebornCore-1.12.2-3.12.0.378-universal.jar
		* reborncoreAPI|Tile (3.12.0.378) from RebornCore-1.12.2-3.12.0.378-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* stevescartsAPI (${version}) from StevesCarts-1.12.2-2.4.27.127.jar
		* stevescartsAPI|FARMS (${version}) from StevesCarts-1.12.2-2.4.27.127.jar
		* techrebornAPI (2.19.0.870) from TechReborn-1.12.2-2.19.0.870-universal.jar
		* Thaumcraft|API (6.0.2) from Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26.jar
```
```
Mods:
  ActuallyAdditions-1.12.2-r144
  ae2stuff-0.7.0.4-mc1.12.2
  AE2WTLib-1.12.2-1.0.0
  aether_ii-1.12.2-1.1.12
  antiqueatlas-1.12.2-4.4.9
  appliedenergistics2-rv6-stable-4
  artisanworktables-1.12.2-1.19.5
  astralsorcery-1.12.2-1.10.3
  athenaeum-1.12.2-1.15.0
  AutoRegLib-1.3-21
  Avaritia-1.12.2-3.2.0.25-universal
  Baubles-1.12-1.5.2
  bdlib-1.14.3.12-mc1.12.2
  BetterAdvancements-1.12.2-0.0.14.68
  BetterFoliage-MC1.12-2.2.0
  BiomesOPlenty-1.12.2-7.0.1.2419-universal
  Bookshelf-1.12.2-2.3.570
  capabilityadapter-1.0.1
  ClientTweaks_1.12.2-3.1.11
  CodeChickenLib-1.12.2-3.2.2.353-universal
  CraftTweaker2-1.12-4.1.13
  CreativeCore_v1.9.35_mc1.12.2
  crimsoncoal-1.12.2-1.0
  CTM-MC1.12.2-0.3.3.22
  Cucumber-1.12.2-1.1.3
  DummyCoreUnofficial-2.4.112.5
  DynamicSurroundings-1.12.2-3.5.1.0BETA
  EerieEntities-1.12.2-1.0.6
  EnderCore-1.12.2-0.5.43
  EnderIO-1.12.2-5.0.38
  EnderIO-zoo-1.12.2-5.0.38
  ExpandedArcanum-1.0.1
  ExtendedCrafting-1.12.2-1.5.0
  ExtraCells-1.12.2-2.6.1a
  FamiliarFauna-1.12.2-1.0.11
  forestry_1.12.2-5.8.2.374
  Forgelin-1.8.2
  ForgeMultipart-1.12.2-2.6.0.79-universal
  furniture-6.1.0-1.12.2
  Futurepack+Addons+1.2
  Futurepack-1.12.2-26.3.461
  gadgetrycore-1.12.2-1.0.0
  gadgetrymachines-1.12.2-1.0.1
  gadgetrytransmission-1.12.2-1.0.0
  GottschCore-mc1.12.2-f14.23.5.2768-v1.5.1
  GregicAdditions-1.12.2-1.3.0
  gregtech-1.12.2-1.0.124
  GTCEBees-1.12.2-1.0.2
  HammerCore-1.12.2-2.0.4.1
  ImmersiveEngineering-0.12-87
  industrialforegoing-1.12.2-1.11.10-223
  IntegrationForegoing-1.12.2-1.8
  IronBackpacks-1.12.2-3.0.8-12
  itemzoom_1.12.2-1.11
  JAOPCA-1.12.2-2.2.8.100
  JAOPCASingularities-1.12.2-2.2.0.8
  jei_1.12.2-4.14.3.237
  jetif-1.12.2-1.2.0
  JustEnoughResources-1.12.2-0.8.10.50
  legiblenei_1.12.2-1.6.12.7
  LibEx-1.12.2-1.0.8
  LittleTiles_v1.5.0-pre122_mc1.12.2
  MagicalPsi-1.3
  MCMultiPart-2.5.3
  Metallurgy-4-Reforged-0.0.3
  moreavaritia-1.12.2-2.3
  MultithreadedNoise-1.12.2-0.0.2
  NaturesAura-b5
  NetherEx-1.12.2-2.0.8
  NotEnoughIDs-1.5.4.3
  obfuscate-0.2.6-1.12.2
  OptiFine_1.12.2_HD_U_E2
  orbis_api-1.12.2-1.1.12a
  OreLib-1.12.2-3.5.1.1BETA
  p455w0rdslib-1.12-2.0.35
  PackagedAuto-1.12.2-1.0.0.2
  PackagedAvaritia-1.12.2-1.0.0.1
  Patchouli-1.0-12
  planarartifice-0.12.2
  portality-1.12.2-1.2.2-14
  Psi-r1.1-62
  Quark-r1.5-134
  RealisticItemDrops-1.2.14
  RebornCore-1.12.2-3.12.0.378-universal
  RebornStorage-1.12.2-3.3.1.76
  RedstoneFlux-1.12-2.1.0.6-universal
  refined_avaritia-1.12.2-2.4
  refinedstorage-1.6.12
  refinedstoragerequestify-1.12.2-1.0.1-2
  Rex's+Additional+Structures+1.12.2++(v.1.8.0)
  Rustic+Thaumaturgy-2.8
  rustic-1.0.13
  SereneSeasons-1.12.2-1.2.13-universal
  simpleundergroundbiomes-1.0.0
  SimplyJetpacks2-1.12.2-2.2.10.63
  Slab_Machines-1.0.4
  SpartanShields-1.12.2-1.4.1
  StevesCarts-1.12.2-2.4.27.127
  stygian-1.0.3
  subh2o-1.12.2-1.5.6
  tc6aspects4jei-0.0.2a
  TechReborn-1.12.2-2.19.0.870-universal
  Tesla-1.12.2-1.0.63
  tesla-core-lib-1.12.2-1.0.15
  Thaumcraft-1.12.2-6.1.BETA26
  thaumcraftresearchloader-1.0
  Thaumic_Gadgets_1.12.2_0.1.5.1_tb.26
  Thaumic+Arcana-1.2.0
  ThaumicAdditions-1.12.2-10r
  thaumicbases-3.2.270.4r
  thaumicenergistics-2.0.0
  ThaumicGrid-1.0.11
  ThaumicJEI-1.12.2-1.5.5-23
  thaumicperiphery-0.3.0
  ThaumicReadoption-0.2.0
  thaumictinkerer-1.12.2-5.0-353c71c
  TheBetweenlands-3.4.1-universal
  themidnight-0.2.0
  Treasure2-mc1.12.2-f14.23.5.2768-v1.2.0
  vehicle-mod-0.33.0-1.12.2
  worleycaves-1.3.0
  WrapUp-1.12-1.1.3
  zettaindustries-1.3-1.12.2-161
```

**Comment by jarodsstuff** [comment]
I can reproduce this issue: https://paste.dimdev.org/uxohoviros.mccrash
