### ISSUE TITLE
Crash when trying to pull out liquids from GTCE centrifuge

### ISSUE THREAD

**Issue by luansantospinto** [EmosewaPixel/GregicAdditions#41]
Not sure yet how this happens, but sometimes when you try to pull out liquids(it happened for me more than once with glue and methane) in a bucket crashes and make the machine glitchy: Breaking with a wrench or restarting minecraft don't fix and you lose the contents/centrifuge. Also, not sure if it happens in any tier, but LV. Anyway, here's the log(GA version 1.3.0, GTCE version 1.0.124): 

`java.lang.ClassCastException: net.minecraftforge.fluids.capability.wrappers.FluidBucketWrapper cannot be cast to net.minecraftforge.fluids.capability.templates.FluidHandlerItemStackSimple
	at gregicadditions.recipes.FluidCellIngredient.apply(FluidCellIngredient.java:44)
	at gregtech.api.recipes.Recipe.matches(Recipe.java:141)
	at gregtech.api.recipes.RecipeMap.findByInputs(RecipeMap.java:225)
	at gregtech.api.recipes.RecipeMap.findRecipe(RecipeMap.java:201)
	at gregtech.api.recipes.RecipeMap.findRecipe(RecipeMap.java:179)
	at gregtech.api.capability.impl.RecipeMapWorkableHandler.findRecipe(RecipeMapWorkableHandler.java:136)
	at gregtech.api.capability.impl.RecipeMapWorkableHandler.update(RecipeMapWorkableHandler.java:118)
	at gregtech.api.metatileentity.MetaTileEntity.update(MetaTileEntity.java:285)
	at gregtech.api.metatileentity.SimpleMachineMetaTileEntity.update(SimpleMachineMetaTileEntity.java:85)
	at gregtech.api.metatileentity.MetaTileEntityHolder.func_73660_a(MetaTileEntityHolder.java:119)
	at net.minecraft.world.World.func_72939_s(World.java:1835)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by EmosewaPixel** [comment]
Since no centrifuge recipes will use Fluid Cells in the next version, this will be fixed.
